services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      # - ./node_modules:/app/node_modules
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
